import Head from 'next/head'
import { Basket } from '../components/Basket'
import { Products } from '../components/Products'
import { getCategoriesFromApi, getProductsFromApi } from '../store'
import styles from '../styles/Home.module.css';
import { SWRConfig } from "swr";

export const getServerSideProps = async () => {
  const products = await getProductsFromApi();
  const categories = await getCategoriesFromApi();
  return {
    props: {
      fallback: {
        "https://northwind.vercel.app/api/products": products,
        "https://northwind.vercel.app/api/categories": categories
      }
    }
  }
}

export default function Home({ fallback }: { fallback: { [key: string]: unknown } }) {
  console.log("rendered index");
  return (
    <div className={styles.container}>
      <Head>
        <title>useSWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the next.js useSWR Test Page
        </h1>
        <SWRConfig value={{ fallback }}>
          <Basket />
          <Products />
        </SWRConfig>
      </main>
    </div>
  )
}
